* Handle this org mode file so we can use it! (as I am a org mode newbie) :-)
* make M4 dict.m4 macro to work with divert() builtin http://www.mkssoftware.com/docs/man1/m4.1.asp
  currently the macro collects all the words ptrs and names into separate macros and then at the end unrolls it.
  (please see BUILD_NAME_TABLE). We need to use divertions instead.
  
* research how to define words with embeded comma inside ( i know it is stupid but who cares :-). 
  So far I am trying to quote it, but it doesn't work for some reasons. The best example is "c," word which happen to fail, 
  and also [ and ] (which are lb and rb respectively)
 
* Make a small program to dump out the places where the executable needs to be backpatched. 
  This will be in the form of builidng two versions of the same core FourK, and binary comparisions.

* Think how to make a smallest Linux executable ever, with proper loading of dynamic symbols, how to do this without ld?
* Think about compressor, maybe ripit from http://en.wikipedia.org/wiki/PAQ =)
* Look at tiny.S
